In [4]:
import numpy as np

In [5]:
arr2 = np.ones((3,10), dtype =int)
print(arr2)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [3]:
arr3 =np.arange(1,31) 
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [8]:
arr3 = np.arange(1,31)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [10]:
arr3 = np.arange(1,31)
arr3 = arr3.reshape(3, 10)
print(arr3)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [14]:
bilet = '123456'
print(bilet[0])

1


In [56]:
arr3 = np.arange(1,31)
arr3 = arr3.reshape(3, 10)
print(arr3([[ 9, 10],
      	      [19, 20],
       	      [29, 30]]))

arr3[ :, 0:7:2] = 1000


TypeError: 'numpy.ndarray' object is not callable

In [70]:
#Задача №1
arr= np.zeros((8,8))

for i in range(8):
    for j in range(8):
        if (i+j)%2==0:
            arr[i,j] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [65]:
#№2
arr= np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i>j:
            arr[i,j] = 5
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5. 5. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5. 5. 5. 0. 0.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 0.]]


In [ ]:
#№3 todo
arr= np.zeros((10,10))
max= 0
for i in range(10):
    for j in range(10):
        if i >j:
            
            arr[i,j]= max +1
            max+=1
            
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  5.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 7.  8.  9. 10.  0.  0.  0.  0.  0.  0.]
 [11. 12. 13. 14. 15.  0.  0.  0.  0.  0.]
 [16. 17. 18. 19. 20. 21.  0.  0.  0.  0.]
 [22. 23. 24. 25. 26. 27. 28.  0.  0.  0.]
 [29. 30. 31. 32. 33. 34. 35. 36.  0.  0.]
 [37. 38. 39. 40. 41. 42. 43. 44. 45.  0.]]


In [16]:
#№4
arr= np.zeros((10,10))
max= 0
for i in range(10):
    for j in range(10):
        if i <j:
            
            arr[j,i]= max +1
            max+=1
            
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3. 11. 18.  0.  0.  0.  0.  0.  0.  0.]
 [ 4. 12. 19. 25.  0.  0.  0.  0.  0.  0.]
 [ 5. 13. 20. 26. 31.  0.  0.  0.  0.  0.]
 [ 6. 14. 21. 27. 32. 36.  0.  0.  0.  0.]
 [ 7. 15. 22. 28. 33. 37. 40.  0.  0.  0.]
 [ 8. 16. 23. 29. 34. 38. 41. 43.  0.  0.]
 [ 9. 17. 24. 30. 35. 39. 42. 44. 45.  0.]]
